[package]
name = "multiplayer-card-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "client-side",
    "server-side",
    "game-logic",
]

[dependencies]
